name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: .NET 
        uses: actions/setup-dotnet@v6
        with: 
          dotnet-version: latest

      - name: Build 
        shell: powershell

        env:
          PRIVATE_CERTIFICATE_BASE64: ${{ secrets.PRIVATE_CERTIFICATE_BASE64 }}
          PRIVATE_CERTIFICATE_PASSWORD: ${{ secrets.PRIVATE_CERTIFICATE_PASSWORD }}
          PRIVATE_CERTIFICATE_FINGERPRINT: ${{ secrets.PRIVATE_CERTIFICATE_FINGERPRINT }}

        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          dotnet tool install --tool-path . --prerelease sign

          $PrivateCertificatePath = "$(Get-Location)\Certificate.pfx"
          $PrivateCertificateBytes = [System.Convert]::FromBase64String($ENV:PRIVATE_CERTIFICATE_BASE64)
          [System.IO.File]::WriteAllBytes($PrivateCertificatePath,  $PrivateCertificateBytes)

          $PublicCertificatePath = "$(Get-Location)\Certificate.cer"
          $PublicCertificateBytes = [System.Convert]::FromBase64String($ENV:PRIVATE_CERTIFICATE_BASE64)
          [System.IO.File]::WriteAllBytes($PublicCertificatePath,  $PublicCertificateBytes)

          dotnet publish "Test.Package.csproj"
          ./sign.exe code certificate-store -cf "$PrivateCertificatePath" -p "$ENV:PRIVATE_CERTIFICATE_PASSWORD" -cfp "$ENV:PRIVATE_CERTIFICATE_FINGERPRINT" "AppPackages\Test.Package_Test\Test.Package.msix" -o "AppPackages\Test.Package.msix"

      - name: Package
        uses: actions/upload-artifact@v7
        with:
           name: package
           path: AppPackages\Test.Package.msix

      - name: Certificate
        uses: actions/upload-artifact@v7
        with:
           name: certificate
           path: Certificate.cer
