name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: .NET 
        uses: actions/setup-dotnet@v6
        with: 
          dotnet-version: latest

      - name: Build 
        shell: powershell

        env:
          PRIVATE_CERTIFICATE_BASE64: ${{ secrets.PRIVATE_CERTIFICATE_BASE64 }}
          PRIVATE_CERTIFICATE_PASSWORD: ${{ secrets.PRIVATE_CERTIFICATE_PASSWORD }}
          PRIVATE_CERTIFICATE_FINGERPRINT: ${{ secrets.PRIVATE_CERTIFICATE_FINGERPRINT }}

        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          $Path = "$(Get-Location)\Certificate.pfx"
          $Bytes = [System.Convert]::FromBase64String($ENV:PRIVATE_CERTIFICATE_BASE64)

          dotnet tool install --tool-path . --prerelease sign
          echo $Path
          [System.IO.File]::WriteAllBytes($Path, $Bytes)