name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-dotnet@v6

      - shell: powershell
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          dotnet tool install --global sign
          dotnet restore Test.Package.csproj